import { test, expect } from '@playwright/test';
test.setTimeout(180000);


test('test', async ({ page }) => {
  await page.goto('https://openmadurai.org/');
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.getByRole('textbox', { name: '············' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('thara@gmail.com');
  await page.getByRole('textbox', { name: '············' }).click();
  await page.getByRole('textbox', { name: '············' }).fill('thara@04');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  const projects = page.getByRole('link', { name: 'Projects' });

await projects.waitFor({
  state: 'visible',
  timeout: 30000
});
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('link', { name: 'My Projects' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('button', { name: 'Add Project' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Project Title' }).click();
  await page.getByRole('textbox', { name: 'Project Title' }).fill('Allobaby landing page');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Summary' }).click();
  await page.getByRole('textbox', { name: 'Summary' }).fill('this project was developed using react');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('it contain about section,feature section, FAQ section, hoe it works section');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('button', { name: 'Upload Image' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByLabel('Upload Image').setInputFiles('input[type="file"]', 'tests/feature.png');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('combobox', { name: 'Category' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('option', { name: 'Development' }).click();
  await page.getByRole('combobox', { name: 'Type' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('option', { name: 'Web Application' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter a tag and press Add or' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter a tag and press Add or' }).fill('react');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Repo Link' }).click();
  await page.getByRole('textbox', { name: 'Repo Link' }).fill('https://allobaby-landing-page.netlify.app/');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Demo Link' }).click();
  await page.getByRole('textbox', { name: 'Demo Link' }).fill('https://allobaby-landing-page.netlify.app/');
  await page.getByRole('textbox', { name: 'Video Link' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Video Link' }).fill('https://allobaby-landing-page.netlify.app/');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Paper Link' }).click();
  await page.getByRole('textbox', { name: 'Paper Link' }).fill('https://allobaby-landing-page.netlify.app/');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('button').nth(3).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter a tag and press Add or' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter a tag and press Add or' }).fill('image');
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.waitForLoadState('domcontentloaded');
  await expect(page.locator('body')).toBeVisible();
  await page.getByRole('button', { name: 'Save' }).click();
});